### ISSUE TITLE
Replace postcss-css-variables with postcss-custom-properties?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/demo-viewer#20]
[PostCSS Custom Properties](https://github.com/postcss/postcss-custom-properties) seems better maintained (and by the PostCSS team) than [PostCSS CSS Variables](https://github.com/MadLittleMods/postcss-css-variables). So replace?

**Comment by jpsc** [comment]
The only thing that I prefer the css-variables is the syntax. It's closer do LESS or SASS like most developers are used to work with. the --var is css next more closer to future css. It's a matter of syntax for the team I think.

**Comment by reinoute** [comment]
I thought the benefit for using postcss was to stay closer to the spec. That's what the CSS variables plugin does and it's enough for this (small) project. If the spec for variables is not changing, is this really an issue?

**Comment by jbmoelker** [comment]
@jpsc I think you're confusing them with [PostCSS Simple Vars](https://github.com/postcss/postcss-simple-vars#readme) which is more SASS like. [PostCSS Custom Properties](https://github.com/postcss/postcss-custom-properties) and [PostCSS CSS Variables](https://github.com/MadLittleMods/postcss-css-variables) both use native CSS variable syntax (`var(--some-color)`). This issue was just about which plugin to use for that, keeping support / maintenance in mind.

**Comment by jpsc** [comment]
Yes. I was. 🐤
Makes sense switching to a more maintained version.
