### ISSUE TITLE
Close viewer-info on module change

### ISSUE THREAD

**Issue by jpsc** [voorhoede/demo-viewer#22]
Now when you switch module on the select option the viewer-info stays open.
Should this be the default behavior ?

This is just and issue on modules that don't have any info to show (like a module without a readme).

**Comment by jbmoelker** [comment]
I think having no info is also informative :) I actually don't mind that it stays open as it also allows you to easily switch between info of different modules. We could close panel if no info available, and disable (or hide) the info button if no info available.

**Comment by jpsc** [comment]
closing to create configurable buttons not only for viewer info
