### ISSUE TITLE
Add "branding" support

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/demo-viewer#5]
Make it easy to add a project / company logo and possibly theming of the viewer.

**Comment by jbmoelker** [comment]
support this through CSS or configure when calling `window.demoViewer()`?

**Comment by jpsc** [comment]
If you want do add a logo and configure a theme you need both.
I would just create a section on documentation pointing the developer to:
- Image that can be changed on the header
- Most important class names eg. `.viewer-info` and what they change

**Comment by jpsc** [comment]
merged
