### ISSUE TITLE
Add semantic-release badge?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/demo-viewer#58]
Like so:

``` markdown
[![semantic-release](https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg)](https://github.com/semantic-release/semantic-release)
```

[![semantic-release](https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg)](https://github.com/semantic-release/semantic-release)

Link to `semantic-release/semantic-release` or `voorhoede/vh-semantic-release-cli`?

**Comment by jpsc** [comment]
Closed by 1da5d7e
